testing k8s monitoring

diff --git a/.github/workflows/deploy-pipeline.yaml b/.github/workflows/deploy-pipeline.yaml
--- a/.github/workflows/deploy-pipeline.yaml
+++ b/.github/workflows/deploy-pipeline.yaml
@@ -167,75 +167,75 @@ jobs:
   #       run: |
   #         ansible-playbook docker-test-playbook.yml -u ec2-user --private-key=/tmp/docker_key.pem -i /tmp/inventory.ini -vvv
     
-  provision-prod-infrastructure-with-terraform:
-    runs-on: ubuntu-latest
-    # needs: push-to-dockerhub
-    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - name: Checkout project sources
-        uses: actions/checkout@v3
-      - name: Setup terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-          terraform_wrapper: false
-      - name: Terraform Init
-        working-directory: terraform-prod
-        id: init
-        run: terraform init
-      - name: Terraform Lint
-        working-directory: terraform-prod
-        id: fmt
-        run: terraform fmt -check
-        continue-on-error: true
-      - name: Terraform Validate
-        working-directory: terraform-prod
-        id: validate
-        run: terraform validate -no-color
-      - name: Terraform Plan
-        working-directory: terraform-prod
-        id: plan
-        run: terraform plan -no-color
-        continue-on-error: true
-      - name: Terraform Plan Status
-        working-directory: terraform-prod
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-      - name: Terraform Apply
-        id: apply
-        working-directory: terraform-prod
-        run: terraform apply -auto-approve
+  # provision-prod-infrastructure-with-terraform:
+  #   runs-on: ubuntu-latest
+  #   # needs: push-to-dockerhub
+  #   # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #   steps:
+  #     - name: Checkout project sources
+  #       uses: actions/checkout@v3
+  #     - name: Setup terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+  #         terraform_wrapper: false
+  #     - name: Terraform Init
+  #       working-directory: terraform-prod
+  #       id: init
+  #       run: terraform init
+  #     - name: Terraform Lint
+  #       working-directory: terraform-prod
+  #       id: fmt
+  #       run: terraform fmt -check
+  #       continue-on-error: true
+  #     - name: Terraform Validate
+  #       working-directory: terraform-prod
+  #       id: validate
+  #       run: terraform validate -no-color
+  #     - name: Terraform Plan
+  #       working-directory: terraform-prod
+  #       id: plan
+  #       run: terraform plan -no-color
+  #       continue-on-error: true
+  #     - name: Terraform Plan Status
+  #       working-directory: terraform-prod
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1
+  #     - name: Terraform Apply
+  #       id: apply
+  #       working-directory: terraform-prod
+  #       run: terraform apply -auto-approve
   
-  deploy-trainschedule-to-eks:
-    needs: provision-prod-infrastructure-with-terraform
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout project sources
-        uses: actions/checkout@v3
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
-      - name: wait until managed nodes spawn
-        run: |
-          sleep 60
-      - name: Run kubernetes deployments
-        working-directory: kubernetes
-        run: |
-          aws eks update-kubeconfig \
-          --name trainschedule \
-          --region ${{ secrets.AWS_REGION }}
-          kubectl create -f trainschedule-deployment-definition.yaml
-          kubectl create -f trainschedule-ingress-definition.yaml
+  # deploy-trainschedule-to-eks:
+  #   needs: provision-prod-infrastructure-with-terraform
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout project sources
+  #       uses: actions/checkout@v3
+  #     - name: Configure AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: us-east-1
+  #     - name: wait until managed nodes spawn
+  #       run: |
+  #         sleep 60
+  #     - name: Run kubernetes deployments
+  #       working-directory: kubernetes
+  #       run: |
+  #         aws eks update-kubeconfig \
+  #         --name trainschedule \
+  #         --region ${{ secrets.AWS_REGION }}
+  #         kubectl create -f trainschedule-deployment-definition.yaml
+  #         kubectl create -f trainschedule-ingress-definition.yaml
       
       
   deploy-monitor-tools-to-eks:
-    needs: deploy-trainschedule-to-eks
+    # needs: deploy-trainschedule-to-eks
     runs-on: ubuntu-latest
     steps:
     - name: Checkout project sources
@@ -246,7 +246,7 @@ jobs:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
-    - name: Run kubernetes deployments
+    - name: login to eks
       working-directory: kubernetes
       run: |
         aws eks update-kubeconfig --name trainschedule --region ${{ secrets.AWS_REGION }}
@@ -260,12 +260,12 @@ jobs:
         helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
         helm repo add grafana https://grafana.github.io/helm-charts
         helm repo update
-    - name: Install Prometheus
-      run: |
-        helm install prometheus prometheus-community/prometheus \
-        --namespace monitoring \
-        --set alertmanager.persistentVolume.storageClass="gp2" \
-        --set server.persistentVolume.storageClass="gp2" \
+    # - name: Install Prometheus
+    #   run: |
+    #     helm install prometheus prometheus-community/prometheus \
+    #     --namespace monitoring \
+    #     --set alertmanager.persistentVolume.storageClass="gp2" \
+    #     --set server.persistentVolume.storageClass="gp2" \
     - name: Install Grafana
       working-directory: monitoring
       run: |
@@ -273,7 +273,7 @@ jobs:
         --namespace monitoring \
         --set persistence.storageClassName="gp2" \
         --set persistence.enabled=true \
-        --set adminPassword= ${{ secrets.GRAFANA_PASSWORD }} \
+        --set adminPassword=${{ secrets.GRAFANA_PASSWORD }} \
         --values grafana.yaml \
         --set service.type="NodePort"
     - name: Install Ingress for Grafana
